---

- hosts: all
  become: true
  tasks:


  - name: install apache2 and php packages for Ubuntu
    package:
      name:
        - apache2
        - libapache2-mod-php
      update_cache: yes
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install HTTPD and PHP packages for CentOS
    package:
      name:
        - httpd
        - php
      update_cache: yes
      state: latest
    when: ansible_distribution == "CentOS"


